// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/janghanul090801/go-backend-clean-architecture-fiber/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ProfileUseCase is an autogenerated mock type for the ProfileUseCase type
type ProfileUseCase struct {
	mock.Mock
}

// GetProfileByID provides a mock function with given fields: c, userID
func (_m *ProfileUseCase) GetProfileByID(c context.Context, userID *uuid.UUID) (*domain.Profile, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByID")
	}

	var r0 *domain.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) (*domain.Profile, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *domain.Profile); ok {
		r0 = rf(c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileUseCase creates a new instance of ProfileUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileUseCase {
	mock := &ProfileUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
